
COMMON: &common
  DEBUG: False
  TESTING: False
  PORT: 4753
  RATINGS:
    STARTER_RATING: 1200
    K_VALUE_21: 15
    K_VALUE_11: 10

  SQLALCHEMY_TRACK_MODIFICATIONS: True

DEVELOPMENT: &development
  <<: *common
  DEBUG: True

PRODUCTION: &production
  <<: *common
  SQLALCHEMY_DATABASE_URI: 'sqlite:///prod.db'

TESTING: &testing
  SQLALCHEMY_DATABASE_URI: 'sqlite://'
